# Default values for busybox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 4
image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: busybox
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

